export const ROAST_QUOTES = [
  'This code was clearly written at 3 AM by someone who had given up on life.',
  'I have seen better architecture in a LEGO set built by a five-year-old.',
  'This is what happens when Stack Overflow is your only teacher.',
  'Whoever wrote this should be legally barred from touching a keyboard.',
  'This code is so bad it could be used as a cybersecurity threat on its own.',
  "I'd rather debug Assembly than spend another minute reading this.",
  'This looks like it was written during a power outage... in 2005.',
  'The TODO comments are the most complete part of this codebase.',
  'Security researchers will be citing this as a case study for decades.',
  'This is not spaghetti code — this is spaghetti that has been in the fridge for three weeks.',
  'Even the compiler is disappointed in you.',
  "This code doesn't just have bugs — it IS the bug.",
  'I have seen more defensive coding in a YOLO challenge.',
  'The commit message should just say "I am so sorry".',
  'This is what technical debt looks like in its natural habitat.',
  'If bad code were a crime, this would carry a life sentence.',
  'Junior developers will look at this and gain confidence they never deserved.',
  'This function does so many things it needs its own project manager.',
  'The variable names suggest the author has never met a variable before.',
  'I expected bad. I was not prepared for this level of bad.',
  'This code has more issues than a legacy Rails app from 2008.',
  "Running this in production is not a career move — it's a career ending.",
  'The indentation alone is a health code violation.',
  'This is the kind of code that makes senior engineers cry quietly at their desks.',
  'Your future self will read this and move countries.'
]
